CREATE TABLE products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50),
    name VARCHAR(100),
    description VARCHAR(255),
    price DECIMAL(10,2),
    category VARCHAR(100),
    reg_date TIMESTAMP,
    mod_date TIMESTAMP,
    state BOOLEAN
);